extends:
  - airbnb-base
  - prettier
env:
  browser: true
plugins:
  - prettier
rules:
  camelcase: "warn"
  no-underscore-dangle: "warn"
globals:
  sodium: true
  videojs: true
  FLUENT_URL: false
  SODIUM_SERVER_URL: false
