dist: xenial
addons:
  apt:
    update: true
    packages:
      - fonts-noto-cjk
services:
  - xvfb
language: node_js
node_js:
  - stable
install:
  - npm --prefix .ci install
script:
  - npm --prefix .ci test
after_script:
  - |
    for f in .ci/screenshots/*; do
      curl \
        -F file="@$f" \
        -F token="${SLACK_TOKEN}" \
        -F channels="${SLACK_CHANNELS}" \
        https://slack.com/api/files.upload
    done
notifications:
  slack:
    rooms:
      - secure: "HHFmpQtSUEU7CY1xd2bXlYToV9tqfkCTV4Uc1b2+MLw1HOWa/n1p+yBKDU1zud0Np42AkBWWlK24vmeR7nK3qDWQb+6GSOae8g+hQ/rcZaUwAGzShpTg8+U9Y60C4/SoGLW0xn4OBhggpTUUzCZqdii+8n8vzy2ScZkWwf7RSyLUWn54yR2vBPJQDi7CIFQ9oQXdUxiTN5VN5b34FAV9L26X/hAQMxrsWSstRowi/X5SpAFRCKsj+jLUE27zxlmJPsKqMrloJYn3Xpbki5QeN0obIcJPOATHIEHDqE7WPBpaA+WSzDttsRoOGQQ4rH6u2Gh0aVlUwQURmHntPtNGdTpiI9WuYRzM9eUHYX8EO0YX2e30EGylYe7CS9aK+yJln0C+rnkqvy+JIRxvN2N+QJwEXJUkdf7ps9c8Z62/fK/NQYNB2S+BrpWxhezhM0ZiPhF5buXIHQJqeMu6M8nLS9CYqQ8ti5YoZ0d5Y/DS4kiTDp3OtlDivYnmTCFTll6Z4d2Zyts3JqauR/UbIWv3q0DYx/Zs9upMIPpPgC6tqpqxxTq0xhEzb38m5EsJRYl6dCGPyF2hNpGfrriBbi3UGXgxe9QMfbvsg1f/4tDPO+j9NiolNpdKnRrJNpdiFsI9k4C323p1Kn4RCjISq+4PnRKQle8N19SQtuF0RpR428Q="
      - secure: "Ux6R+F2rXvmmoH8GGhivhgWgQyo9kNBqGRR//FNTouW5SXTLG8rP8zTi/dyT1fhx7o7ZZn+4a8oJd7ZlRVQFboPfZAFNOk/XSd8YxP04STCuS2ZpAiWZFsm8W0iyfZFswK1VU6rijkDmvKNOTwpKtmj/Vo5RSBHhvurc1wJTsusmN9Z9MBrOARgrWtymImnuNjYD3/QFnI06c0KWAQL0GEClpOJRGgzH6YA8BHg52v0NUY7pHfggAM4gokqmg8AtYweX2KsVMmcxZCN3Vs7w/BSgchX1CO0qdRCaKmQq6wSsrxeWC8oaeSs/Cju9KoabQoxE2B2xspZBcHaULbH7bbT2p5RS19S8NK+c6IKxM0Lz9fxV0Oq17PF2lBDv1KcYf31B0vM+B/VYAHyWI+Z9BYV2VDbSco83qMuirrM35GN4MWXde7MOddkCA+XsYjGLkiPVkd7DDyoo2Q0YBXaNH3raRfKr3DhYxyy2/T7bz1ckrmtZygmv1x1w9+rp7IVmrW+jEur+mHh/RUvnQIN/q+67pCDIDWm8sYzOPa20ThgPT8zyupZWKTGuu8sBefF7fUP7pYa5CfvXopLLotY/Atj8JdLsVxuup11JqDLhl19BmCzVxU8/+btxn9h5VNr6dpbFaB+Gld/LAOIzd84snL2MVvk0hfm8tWvb8huegVw="
    on_success: change
    on_failure: always
  email:
    recipients:
      - secure: "UgBZu2pwlAznWOwBIdnRIs/iIPAyEqI1Sd4v3d6dre/35QT/2zLxHjBOnQmZ7knMWGn2j8+N+VtTWcu670l0ByeCanCXiCzEgl2ITNllRl4WHZoFQVDS17lCQ1JVxWeq2rppHpakB5VYPIF6QlBqUjZWqdm8wW7wGTQg3yEumRrTYM6KXE5V1j1/U4IByvsKzNqRxXZQsS2jVg1RDqTgMZfaWZbNANuJXbc1wKmgC7vmTjz4ShGrTzoS9Q9X8fX5zRK1N8fWatE/bt4rccPNorNY7BLoj41PJ2OUeHp2FhywmYV3rM6pA4e6YJckYCag9+hy8ggLhXFE3QmxELiSVGg53CSYYjQPTqusjXT+D0Qbysd7m6Lv4uPpIz3/pNiGA42SR+7qcy6K0jFV31DXkRgYegRx1a2gYRJhn1COjlaBIBlVt0irzA3uPM0aCiRu7IbB6P70CdTzD4WTpF4M6ff+yKkIaNeOIpL0Nv+Ljn9bv/6wkGy5E6Efk4hmbkccKfPVkpW53k8ipfVsXCLMVgnD+ZiAbZgiC3QXQuvT/6fa6zHq8OhfaQPgXsJnod9cAJhSJYcci+AP+wnr9qQzchmhQHY4Jh03kwz7QBvEPGMXY/e8BXPe8+H3/tvWF0BR2CY5xd0HqI8onZd5CgXdCU7agZK9SYyFQ8Pea3J5pLY="
    on_success: never
    on_failure: always
