[build]
  publish = "dist"
  command = "bin/build"
[[redirects]]
  from = "/"
  to = "/videomark.zip"
[[redirects]]
  from = "/prod"
  to = "/videomark.zip"
[[redirects]]
  from = "/dev"
  to = "/videomark-dev.zip"
[[redirects]]
  from = "/prod-xpi"
  to = "/videomark-firefox.xpi"
[[redirects]]
  from = "/dev-xpi"
  to = "/videomark-dev-firefox.xpi"
