[build]
  publish = "dist"
  command = "bin/build"
[[redirects]]
  from = "/"
  to = "/webvideomark.zip"
[[redirects]]
  from = "/prod"
  to = "/webvideomark.zip"
[[redirects]]
  from = "/dev"
  to = "/webvideomark-dev.zip"
[[redirects]]
  from = "/prod-xpi"
  to = "/webvideomark.xpi"
[[redirects]]
  from = "/dev-xpi"
  to = "/webvideomark-dev.xpi"
