extends:
  - airbnb-base
  - prettier
env:
  browser: true
plugins:
  - prettier
rules:
  camelcase: "off"
  no-underscore-dangle: "off"
  class-methods-use-this: "off"
globals:
  sodium: true
  videojs: true
  FLUENT_URL: false
  SODIUM_SERVER_URL: false
  PEAK_TIME_LIMIT_URL: false
