name: build
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: node
        run: echo "::set-output name=version::$(cat .nvmrc)"
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.node.version }}"
          cache: yarn
      - run: yarn
      - run: yarn build

  safari:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s "/Applications/Xcode_12.5.1.app/Contents/Developer"
      - id: node
        run: echo "::set-output name=version::$(cat .nvmrc)"
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.node.version }}"
          cache: yarn
      - run: yarn
      - run: yarn build-safari
      - uses: actions/upload-artifact@v2
        with:
          name: webvideomark-safari-extension.zip
          path: dist/webvideomark-safari-extension.zip
