name: build
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn
        env: { PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true" }
      - run: yarn build

  safari:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s "/Applications/Xcode_12.5.1.app/Contents/Developer"
      - uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn
        env: { PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true" }
      - run: yarn build-safari
      - uses: actions/upload-artifact@v2
        with:
          name: webvideomark-safari-extension.zip
          path: dist/webvideomark-safari-extension.zip
