name: ubuntu
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: sudo apt-get update
      - run: sudo apt-get install xvfb fonts-noto-cjk chromium-browser
      - run: npm --prefix .ci install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      - run: npm --prefix .ci test
